# Generated by Django 3.1.4 on 2020-12-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20201203_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
    ]
