# Generated by Django 3.1.3 on 2020-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likebookuser',
            name='rate',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
