# Generated by Django 3.1.3 on 2020-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_likebookuser_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='likes',
            new_name='count_all_stars',
        ),
        migrations.AddField(
            model_name='book',
            name='count_rated_user',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
