# Generated by Django 3.1.3 on 2020-12-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20201212_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='count_rated_user',
            new_name='count_rated_users',
        ),
    ]
