# Generated by Django 3.1.3 on 2020-12-16 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0022_auto_20201212_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, help_text='ну это типа погоняло книги', max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='users_like',
            field=models.ManyToManyField(related_name='liked_comment', through='manager.LikeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
