# Generated by Django 3.1.3 on 2020-12-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0023_auto_20201216_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTale',
            fields=[
                ('title', models.CharField(db_column='title', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, help_text='ну это типо погоняло книги', max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='users_like',
            field=models.ManyToManyField(related_name='liked_books', through='manager.LikeBookUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likebookuser',
            name='rate',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='TestComment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.testtale')),
            ],
        ),
        migrations.CreateModel(
            name='TestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.testtale')),
            ],
        ),
    ]
